/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "NSObject.h"


@protocol MusicGridViewDataSource <NSObject>
- (void)decodeArtworkForRow:(unsigned)row withNumberOfColumns:(unsigned)columns andNumberOfItems:(unsigned)items waitUntilDone:(BOOL)done;
@optional
- (CGRect)gridView:(id)view frameForSectionIndexGivenProposedFrame:(CGRect)sectionIndexGivenProposedFrame;
- (unsigned)gridView:(id)view itemIndexForSectionTitleIndex:(unsigned)sectionTitleIndex;
@required
- (id)gridView:(id)view viewForIndexPath:(id)indexPath reusingView:(id)view3;
@optional
- (id)localizedSectionIndexTitlesForGridView:(id)gridView;
@required
- (unsigned)numberOfColumnsInGridView:(id)gridView;
- (unsigned)numberOfItemsInGridView:(id)gridView;
@optional
- (BOOL)shouldPrefetchArtworkForGridView:(id)gridView;
- (BOOL)showsIndexBarForGridView:(id)gridView;
@end

