/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import "MusicGridViewDataSource.h"
#import <UIKit/UIViewController.h>
#import "MusicGridViewDelegate.h"

@class MusicSectionHeaderView, MusicGridView, MusicQueryDataSource;

__attribute__((visibility("hidden")))
@interface MusicGridViewController : UIViewController <MusicGridViewDataSource, MusicGridViewDelegate> {
	MusicQueryDataSource *_dataSource;
	MusicSectionHeaderView *_globalHeaderView;
	Class _gridConfigurationClass;
	MusicGridView *_gridView;
	BOOL _reloadWhenVisible;
	BOOL _visible;
}
@property(readonly, assign, nonatomic) MusicQueryDataSource *dataSource;
@property(readonly, assign, nonatomic) Class gridConfigurationClass;
@property(readonly, assign, nonatomic) MusicGridView *gridView;
- (id)init;
- (id)initWithDataSource:(id)dataSource gridConfigurationClass:(Class)aClass;
- (void)_dataSourceDidInvalidateNotification:(id)_dataSource;
- (void)_updateGlobalHeaderView;
- (void)addAllEntitiesToPickerOverlay;
- (void)dataSourceDidInvalidate;
- (void)dealloc;
- (void)decodeArtworkForRow:(unsigned)row withNumberOfColumns:(unsigned)columns andNumberOfItems:(unsigned)items waitUntilDone:(BOOL)done;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (float)globalHeaderHeight;
- (CGRect)gridView:(id)view frameForSectionIndexGivenProposedFrame:(CGRect)sectionIndexGivenProposedFrame;
- (unsigned)gridView:(id)view itemIndexForSectionTitleIndex:(unsigned)sectionTitleIndex;
- (id)gridView:(id)view viewForIndexPath:(id)indexPath reusingView:(id)view3;
- (void)gridViewWillBeginDragging:(id)gridView;
- (BOOL)isVisibleInMorePopover;
- (void)loadView;
- (id)localizedSectionIndexTitlesForGridView:(id)gridView;
- (unsigned)numberOfColumnsInGridView:(id)gridView;
- (unsigned)numberOfItemsInGridView:(id)gridView;
- (void)reloadData;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (BOOL)shouldPrefetchArtworkForGridView:(id)gridView;
- (BOOL)showsIndexBarForGridView:(id)gridView;
- (float)topScrollInset;
- (void)viewDidAppear:(BOOL)view;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
- (void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
@end

