/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MusicGridViewDelegate <NSObject>
@optional
- (void)gridView:(id)view didSelectViewAtIndexPath:(id)indexPath;
- (void)gridViewWillBeginDragging:(id)gridView;
@end

