/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Music~ipad-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIButton, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface MusicHeaderView : UIView {
	UILabel *_label;
	UIButton *_leftButton;
	UILabel *_subtitleLabel;
	NSArray *_rightButtons;
}
@property(retain, nonatomic) UIButton *leftButton;
@property(copy, nonatomic) NSArray *rightButtons;
@property(readonly, assign, nonatomic) float scrollInset;
@property(copy, nonatomic) NSString *subtitle;
@property(copy, nonatomic) NSString *title;
- (id)initWithFrame:(CGRect)frame;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
- (void)layoutSubviews;
- (CGSize)sizeThatFits:(CGSize)fits;
@end

